/**
 * 内置音色表：1:1 移植自原 tts-tool.html 的 LANG_VOICES。
 * 注：用户从 API 刷新后，缓存的音色会覆盖此数据。
 */
import type { LangVoicesMap, Voice } from '@/types/voice';

/** Helper: 把 [id, name][] 映射成 Voice[]，并保证类型安全 */
const toVoices = (entries: ReadonlyArray<readonly [string, string]>): Voice[] =>
  entries.map(([id, name]): Voice => ({ id, name }));

export const BUILTIN_LANG_VOICES: LangVoicesMap = {
  zh: {
    label: '中文（普通话）',
    langBoost: 'Chinese',
    voices: toVoices([
      ['male-qn-qingse', '青涩青年'],
      ['male-qn-jingying', '精英青年'],
      ['male-qn-badao', '霸道青年'],
      ['male-qn-daxuesheng', '青年大学生'],
      ['female-shaonv', '少女'],
      ['female-yujie', '御姐'],
      ['female-chengshu', '成熟女性'],
      ['female-tianmei', '甜美女性'],
      ['male-qn-qingse-jingpin', '青涩青年β'],
      ['male-qn-jingying-jingpin', '精英青年β'],
      ['male-qn-badao-jingpin', '霸道青年β'],
      ['male-qn-daxuesheng-jingpin', '大学生β'],
      ['female-shaonv-jingpin', '少女β'],
      ['female-yujie-jingpin', '御姐β'],
      ['female-chengshu-jingpin', '成熟女性β'],
      ['female-tianmei-jingpin', '甜美女性β'],
      ['clever_boy', '聪明男童'],
      ['cute_boy', '可爱男童'],
      ['lovely_girl', '萌萌女童'],
      ['cartoon_pig', '卡通猪小琪'],
      ['bingjiao_didi', '病娇弟弟'],
      ['junlang_nanyou', '俊朗男友'],
      ['chunzhen_xuedi', '纯真学弟'],
      ['lengdan_xiongzhang', '冷淡学长'],
      ['badao_shaoye', '霸道少爷'],
      ['tianxin_xiaoling', '甜心小玲'],
      ['qiaopi_mengmei', '俏皮萌妹'],
      ['wumei_yujie', '妩媚御姐'],
      ['diadia_xuemei', '嗲嗲学妹'],
      ['danya_xuejie', '淡雅学姐'],
      ['presenter_male', '男声播报'],
      ['presenter_female', '女声播报'],
      ['Chinese (Mandarin)_Reliable_Executive', '沉稳高管'],
      ['Chinese (Mandarin)_News_Anchor', '新闻女声'],
      ['Chinese (Mandarin)_Mature_Woman', '傲娇御姐'],
      ['Chinese (Mandarin)_Unrestrained_Young_Man', '不羁青年'],
      ['Arrogant_Miss', '嚣张小姐'],
      ['Robot_Armor', '机械战甲'],
      ['Chinese (Mandarin)_Kind-hearted_Antie', '热心大婶'],
      ['Chinese (Mandarin)_HK_Flight_Attendant', '港普空姐'],
      ['Chinese (Mandarin)_Humorous_Elder', '搞笑大爷'],
      ['Chinese (Mandarin)_Gentleman', '温润男声'],
      ['Chinese (Mandarin)_Warm_Bestie', '温暖闺蜜'],
      ['Chinese (Mandarin)_Male_Announcer', '播报男声'],
      ['Chinese (Mandarin)_Sweet_Lady', '甜美女声'],
      ['Chinese (Mandarin)_Southern_Young_Man', '南方小哥'],
      ['Chinese (Mandarin)_Wise_Women', '阅历姐姐'],
      ['Chinese (Mandarin)_Gentle_Youth', '温润青年'],
      ['Chinese (Mandarin)_Warm_Girl', '温暖少女'],
      ['Chinese (Mandarin)_Kind-hearted_Elder', '花甲奶奶'],
      ['Chinese (Mandarin)_Cute_Spirit', '憨憨萌兽'],
      ['Chinese (Mandarin)_Radio_Host', '电台男主播'],
      ['Chinese (Mandarin)_Lyrical_Voice', '抒情男声'],
      ['Chinese (Mandarin)_Straightforward_Boy', '率真弟弟'],
      ['Chinese (Mandarin)_Sincere_Adult', '真诚青年'],
      ['Chinese (Mandarin)_Gentle_Senior', '温柔学姐'],
      ['Chinese (Mandarin)_Stubborn_Friend', '嘴硬竹马'],
      ['Chinese (Mandarin)_Crisp_Girl', '清脆少女'],
      ['Chinese (Mandarin)_Pure-hearted_Boy', '清澈邻弟'],
      ['Chinese (Mandarin)_Soft_Girl', '柔和少女'],
    ]),
  },
  yue: {
    label: '中文（粤语）',
    langBoost: 'Chinese,Yue',
    voices: toVoices([
      ['Cantonese_ProfessionalHost（F）', '专业女主持'],
      ['Cantonese_GentleLady', '温柔女声'],
      ['Cantonese_ProfessionalHost（M）', '专业男主持'],
      ['Cantonese_PlayfulMan', '活泼男声'],
      ['Cantonese_CuteGirl', '可爱女孩'],
      ['Cantonese_KindWoman', '善良女声'],
    ]),
  },
  en: {
    label: 'English',
    langBoost: 'English',
    voices: toVoices([
      ['English_Graceful_Lady', 'Graceful Lady'],
      ['English_Trustworthy_Man', 'Trustworthy Man'],
      ['English_Aussie_Bloke', 'Aussie Bloke'],
      ['English_Whispering_girl', 'Whispering Girl'],
      ['English_Diligent_Man', 'Diligent Man'],
      ['English_Gentle-voiced_man', 'Gentle Man'],
      ['Santa_Claus', 'Santa Claus'],
      ['Grinch', 'Grinch'],
      ['Rudolph', 'Rudolph'],
      ['Arnold', 'Arnold'],
      ['Charming_Santa', 'Charming Santa'],
      ['Charming_Lady', 'Charming Lady'],
      ['Sweet_Girl', 'Sweet Girl'],
      ['Cute_Elf', 'Cute Elf'],
      ['Attractive_Girl', 'Attractive Girl'],
      ['Serene_Woman', 'Serene Woman'],
    ]),
  },
  ja: {
    label: '日本語',
    langBoost: 'Japanese',
    voices: toVoices([
      ['Japanese_IntellectualSenior', 'Intellectual Senior'],
      ['Japanese_DecisivePrincess', 'Decisive Princess'],
      ['Japanese_LoyalKnight', 'Loyal Knight'],
      ['Japanese_DominantMan', 'Dominant Man'],
      ['Japanese_SeriousCommander', 'Serious Commander'],
      ['Japanese_ColdQueen', 'Cold Queen'],
      ['Japanese_DependableWoman', 'Dependable Woman'],
      ['Japanese_GentleButler', 'Gentle Butler'],
      ['Japanese_KindLady', 'Kind Lady'],
      ['Japanese_CalmLady', 'Calm Lady'],
      ['Japanese_OptimisticYouth', 'Optimistic Youth'],
      ['Japanese_GenerousIzakayaOwner', 'Izakaya Owner'],
      ['Japanese_SportyStudent', 'Sporty Student'],
      ['Japanese_InnocentBoy', 'Innocent Boy'],
      ['Japanese_GracefulMaiden', 'Graceful Maiden'],
    ]),
  },
  ko: {
    label: '한국어',
    langBoost: 'Korean',
    voices: toVoices([
      ['Korean_SweetGirl', 'Sweet Girl'],
      ['Korean_CheerfulBoyfriend', 'Cheerful Boyfriend'],
      ['Korean_EnchantingSister', 'Enchanting Sister'],
      ['Korean_ShyGirl', 'Shy Girl'],
      ['Korean_ReliableSister', 'Reliable Sister'],
      ['Korean_StrictBoss', 'Strict Boss'],
      ['Korean_SassyGirl', 'Sassy Girl'],
      ['Korean_ChildhoodFriendGirl', 'Childhood Friend'],
      ['Korean_PlayboyCharmer', 'Playboy Charmer'],
      ['Korean_ElegantPrincess', 'Elegant Princess'],
      ['Korean_BraveFemaleWarrior', 'Brave Warrior'],
      ['Korean_BraveYouth', 'Brave Youth'],
      ['Korean_CalmLady', 'Calm Lady'],
      ['Korean_EnthusiasticTeen', 'Enthusiastic Teen'],
      ['Korean_SoothingLady', 'Soothing Lady'],
      ['Korean_IntellectualSenior', 'Intellectual Senior'],
      ['Korean_LonelyWarrior', 'Lonely Warrior'],
      ['Korean_MatureLady', 'Mature Lady'],
      ['Korean_InnocentBoy', 'Innocent Boy'],
      ['Korean_CharmingSister', 'Charming Sister'],
      ['Korean_AthleticStudent', 'Athletic Student'],
      ['Korean_BraveAdventurer', 'Brave Adventurer'],
      ['Korean_CalmGentleman', 'Calm Gentleman'],
      ['Korean_WiseElf', 'Wise Elf'],
      ['Korean_CheerfulCoolJunior', 'Cheerful Junior'],
      ['Korean_DecisiveQueen', 'Decisive Queen'],
      ['Korean_ColdYoungMan', 'Cold Young Man'],
      ['Korean_MysteriousGirl', 'Mysterious Girl'],
      ['Korean_QuirkyGirl', 'Quirky Girl'],
      ['Korean_ConsiderateSenior', 'Considerate Senior'],
      ['Korean_CheerfulLittleSister', 'Cheerful Little Sis'],
      ['Korean_DominantMan', 'Dominant Man'],
      ['Korean_AirheadedGirl', 'Airheaded Girl'],
      ['Korean_ReliableYouth', 'Reliable Youth'],
      ['Korean_FriendlyBigSister', 'Friendly Big Sister'],
      ['Korean_GentleBoss', 'Gentle Boss'],
      ['Korean_ColdGirl', 'Cold Girl'],
      ['Korean_HaughtyLady', 'Haughty Lady'],
      ['Korean_CharmingElderSister', 'Charming Elder Sis'],
      ['Korean_IntellectualMan', 'Intellectual Man'],
      ['Korean_CaringWoman', 'Caring Woman'],
      ['Korean_WiseTeacher', 'Wise Teacher'],
      ['Korean_ConfidentBoss', 'Confident Boss'],
      ['Korean_AthleticGirl', 'Athletic Girl'],
      ['Korean_PossessiveMan', 'Possessive Man'],
      ['Korean_GentleWoman', 'Gentle Woman'],
      ['Korean_CockyGuy', 'Cocky Guy'],
      ['Korean_ThoughtfulWoman', 'Thoughtful Woman'],
      ['Korean_OptimisticYouth', 'Optimistic Youth'],
    ]),
  },
  es: {
    label: 'Español',
    langBoost: 'Spanish',
    voices: toVoices([
      ['Spanish_SereneWoman', 'Serene Woman'],
      ['Spanish_MaturePartner', 'Mature Partner'],
      ['Spanish_CaptivatingStoryteller', 'Storyteller'],
      ['Spanish_Narrator', 'Narrator'],
      ['Spanish_WiseScholar', 'Wise Scholar'],
      ['Spanish_Kind-heartedGirl', 'Kind Girl'],
      ['Spanish_DeterminedManager', 'Determined Manager'],
      ['Spanish_BossyLeader', 'Bossy Leader'],
      ['Spanish_ReservedYoungMan', 'Reserved Young Man'],
      ['Spanish_ConfidentWoman', 'Confident Woman'],
    ]),
  },
  fr: {
    label: 'Français',
    langBoost: 'French',
    voices: toVoices([
      ['French_Male_Speech_New', 'Level-Headed Man'],
      ['French_Female_News Anchor', 'Patient Female'],
      ['French_CasualMan', 'Casual Man'],
      ['French_MovieLeadFemale', 'Movie Lead'],
      ['French_FemaleAnchor', 'Female Anchor'],
      ['French_MaleNarrator', 'Male Narrator'],
    ]),
  },
  de: {
    label: 'Deutsch',
    langBoost: 'German',
    voices: toVoices([
      ['German_FriendlyMan', 'Friendly Man'],
      ['German_SweetLady', 'Sweet Lady'],
      ['German_PlayfulMan', 'Playful Man'],
    ]),
  },
  pt: {
    label: 'Português',
    langBoost: 'Portuguese',
    voices: toVoices([
      ['Portuguese_SentimentalLady', 'Sentimental Lady'],
      ['Portuguese_BossyLeader', 'Bossy Leader'],
      ['Portuguese_Wiselady', 'Wise Lady'],
      ['Portuguese_ConfidentWoman', 'Confident Woman'],
      ['Portuguese_SereneWoman', 'Serene Woman'],
      ['Portuguese_Narrator', 'Narrator'],
      ['Portuguese_SweetGirl', 'Sweet Girl'],
      ['Portuguese_AttractiveGirl', 'Attractive Girl'],
    ]),
  },
  ru: {
    label: 'Русский',
    langBoost: 'Russian',
    voices: toVoices([
      ['Russian_HandsomeChildhoodFriend', 'Handsome Friend'],
      ['Russian_BrightHeroine', 'Bright Queen'],
      ['Russian_AmbitiousWoman', 'Ambitious Woman'],
      ['Russian_ReliableMan', 'Reliable Man'],
      ['Russian_CrazyQueen', 'Crazy Girl'],
      ['Russian_PessimisticGirl', 'Pessimistic Girl'],
      ['Russian_AttractiveGuy', 'Attractive Guy'],
      ['Russian_Bad-temperedBoy', 'Bad-tempered Boy'],
    ]),
  },
  id: {
    label: 'Bahasa Indonesia',
    langBoost: 'Indonesian',
    voices: toVoices([
      ['Indonesian_SweetGirl', 'Sweet Girl'],
      ['Indonesian_CharmingGirl', 'Charming Girl'],
      ['Indonesian_CalmWoman', 'Calm Woman'],
      ['Indonesian_ConfidentWoman', 'Confident Woman'],
      ['Indonesian_CaringMan', 'Caring Man'],
      ['Indonesian_GentleGirl', 'Gentle Girl'],
    ]),
  },
  ar: {
    label: 'العربية',
    langBoost: 'Arabic',
    voices: toVoices([
      ['Arabic_CalmWoman', 'Calm Woman'],
      ['Arabic_FriendlyGuy', 'Friendly Guy'],
    ]),
  },
  it: {
    label: 'Italiano',
    langBoost: 'Italian',
    voices: toVoices([
      ['Italian_BraveHeroine', 'Brave Heroine'],
      ['Italian_Narrator', 'Narrator'],
    ]),
  },
  tr: {
    label: 'Türkçe',
    langBoost: 'Turkish',
    voices: toVoices([
      ['Turkish_CalmWoman', 'Calm Woman'],
      ['Turkish_Trustworthyman', 'Trustworthy Man'],
    ]),
  },
  nl: {
    label: 'Nederlands',
    langBoost: 'Dutch',
    voices: toVoices([
      ['Dutch_kindhearted_girl', 'Kind Girl'],
      ['Dutch_bossy_leader', 'Bossy Leader'],
    ]),
  },
  th: {
    label: 'ไทย',
    langBoost: 'Thai',
    voices: toVoices([
      ['Thai_male_1_sample8', 'Serene Man'],
      ['Thai_female_1_sample1', 'Confident Woman'],
    ]),
  },
  vi: {
    label: 'Tiếng Việt',
    langBoost: 'Vietnamese',
    voices: toVoices([['Vietnamese_kindhearted_girl', 'Kind Girl']]),
  },
  uk: {
    label: 'Українська',
    langBoost: 'Ukrainian',
    voices: toVoices([
      ['Ukrainian_CalmWoman', 'Calm Woman'],
      ['Ukrainian_WiseScholar', 'Wise Scholar'],
    ]),
  },
  pl: {
    label: 'Polski',
    langBoost: 'Polish',
    voices: toVoices([
      ['Polish_male_1_sample4', 'Male Narrator'],
      ['Polish_female_1_sample1', 'Calm Woman'],
    ]),
  },
  hi: {
    label: 'हिन्दी',
    langBoost: 'Hindi',
    voices: toVoices([
      ['hindi_male_1_v2', 'Trustworthy Advisor'],
      ['hindi_female_1_v2', 'News Anchor'],
    ]),
  },
};

/**
 * 已知模型列表
 */
export const TTS_MODELS: { value: string; label: string }[] = [
  { value: 'speech-2.8-hd', label: 'speech-2.8-hd（最新高清）' },
  { value: 'speech-2.8-turbo', label: 'speech-2.8-turbo（最新快速）' },
  { value: 'speech-2.6-hd', label: 'speech-2.6-hd' },
  { value: 'speech-2.6-turbo', label: 'speech-2.6-turbo' },
];
